import type { Metadata } from "next";
// import "./globals.css";
import ChakraProviders from "@/app/ChakraProvider";
import QueryProviders from "@/app/QueryProviders";
import TheHeader from "./TheHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProviders>
          <ChakraProviders>
            <TheHeader />
            {children}
          </ChakraProviders>
        </QueryProviders>
      </body>
    </html>
  );
}
