name: Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Login to Dockerhub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Environment Variables
      run: |
        echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
        echo "NEXT_PUBLIC_KAKAO_REST_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_KEY }}" >> .env
        echo "NEXT_PUBLIC_NAVER_SECRET=${{ secrets.NEXT_PUBLIC_NAVER_SECRET  }}" >> .env

    - name: build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodteacher-fe-2:${{ github.sha }}
    
    - name: Discord notification on build failure
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }}-2 build failed.'

    - name: Update docker image name
      run: |
        git init
        git config --global user.email "gracehpark@naver.com"
        git config --global user.name "gracehpark0120"
        git clone https://${{ secrets.GIT_TOKEN }}@github.com/foodteacher/devops.git
        cd devops/fe
        sed -i "s|gracehpark/foodteacher-fe-2:.*|gracehpark/foodteacher-fe-2:${{ github.sha }}|g" fe-2-deployment.yaml
        git commit -am "Update Docker Image Name"
        git push

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }}-2 has been deployed.'
  
