name: Build and Push FE

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy (v2 for main, dev for dev)'
        required: true
        default: 'v2'
        options:
          - v2
          - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.environment == 'v2' && 'main' || 'dev' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Login to Dockerhub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Environment Variables
      run: |
        echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_2 }}" >> .env
        echo "NEXT_PUBLIC_KAKAO_REST_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_KEY }}" >> .env
        echo "NEXT_PUBLIC_NAVER_SECRET=${{ secrets.NEXT_PUBLIC_NAVER_SECRET  }}" >> .env
        echo "NEXT_PUBLIC_NAVER_CLIENT_ID=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_ID }}" >> .env
        echo "NEXT_PUBLIC_NAVER_REST_ID=${{ secrets.NEXT_PUBLIC_NAVER_REST_ID }}" >> .env

    - name: Get image tag(version)
      id: image
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo VERSION=$VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/foodteacher-fe-${{ github.event.inputs.environment == 'v2' && '2' || 'dev' }}:${{ steps.image.outputs.version }}

    - name: Discord notification on build failure
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} build failed for ${{ github.event.inputs.environment }} environment.'

    - name: Update docker image name for Helm
      run: |
        git clone https://${{ secrets.GIT_TOKEN }}@github.com/foodteacher/foodteacher-helm.git
        cd foodteacher-helm/apps/foodteacher-fe
        if [[ "${{ github.event.inputs.environment }}" == "v2" ]]; then
          sed -i '/v2_image:/,/tag:/ s/tag: ".*"/tag: "${{ steps.image.outputs.version }}"/' values.yaml
        elif [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
          sed -i '/dev_image:/,/tag:/ s/tag: ".*"/tag: "${{ steps.image.outputs.version }}"/' values.yaml
        fi
        git config --global user.email "gracehpark@naver.com"
        git config --global user.name "gracehpark0120"
        git commit -am "Update Docker Image Name for ${{ github.event.inputs.environment }} environment"
        git push

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to ${{ github.event.inputs.environment }} environment.'
